steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/images/${_APP_NAME}:${COMMIT_SHA}",
        "-t",
        "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/images/${_APP_NAME}:latest",
        "-f",
        "./apps/docs/Dockerfile",
        ".",
      ]
timeout: 300s
images:
  - ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/images/${_APP_NAME}:${COMMIT_SHA}
  - ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/images/${_APP_NAME}:latest
substitutions:
  _APP_NAME: NONE
options:
  logging: CLOUD_LOGGING_ONLY
