steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/${PROJECT_ID}/github.com/${REPO_FULL_NAME}:latest",
        "-f",
        "./apps/discord-bot/Dockerfile",
        ".",
      ]
images:
  - gcr.io/${PROJECT_ID}/github.com/${REPO_FULL_NAME}:latest
options:
  logging: CLOUD_LOGGING_ONLY
